/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author ruirui
 */
public class CreateJPanel extends javax.swing.JPanel {

    Person person;
    
    /**
     * Creates new form createJPanel
     */
    public CreateJPanel(Person p) {
        person = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtDLNum = new javax.swing.JTextField();
        lblDLNum = new javax.swing.JLabel();
        txtDLState = new javax.swing.JTextField();
        lblDLState = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblWAddressL1 = new javax.swing.JLabel();
        txtWAddressL1 = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtWAddressL2 = new javax.swing.JTextField();
        lblWAddressL2 = new javax.swing.JLabel();
        txtWCity = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        lblWState = new javax.swing.JLabel();
        txtWZip = new javax.swing.JTextField();
        lblWZip = new javax.swing.JLabel();
        txtWPhone = new javax.swing.JTextField();
        lblWPhone = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblMStat = new javax.swing.JLabel();
        lblLang = new javax.swing.JLabel();
        txtLang = new javax.swing.JTextField();
        txtMStat = new javax.swing.JTextField();
        lblPWeb = new javax.swing.JLabel();
        txtPWeb = new javax.swing.JTextField();
        lblCOri = new javax.swing.JLabel();
        txtCOri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblWAddress = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblLocAddressL1 = new javax.swing.JLabel();
        txtLocAddressL1 = new javax.swing.JTextField();
        txtLocAddressL2 = new javax.swing.JTextField();
        lblLocAddressL2 = new javax.swing.JLabel();
        txtLocCity = new javax.swing.JTextField();
        lblLAddress = new javax.swing.JLabel();
        lblLocCity = new javax.swing.JLabel();
        txtLocState = new javax.swing.JTextField();
        lblLocState = new javax.swing.JLabel();
        txtLocZip = new javax.swing.JTextField();
        lblLocZip = new javax.swing.JLabel();
        txtLocPhone = new javax.swing.JTextField();
        lblLocPhone = new javax.swing.JLabel();
        lblHAddressL2 = new javax.swing.JLabel();
        txtHCity = new javax.swing.JTextField();
        lblHCity = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        txtHZip = new javax.swing.JTextField();
        lblHZip = new javax.swing.JLabel();
        txtHPhone = new javax.swing.JTextField();
        lblHPhone = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblHAddressL1 = new javax.swing.JLabel();
        txtHAddressL1 = new javax.swing.JTextField();
        txtHAddressL2 = new javax.swing.JTextField();
        lblHAddress = new javax.swing.JLabel();

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        lblFName.setText("First Name");

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        lblLName.setText("Last Name");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        lblPhone.setText("Phone");

        txtDLNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDLNumActionPerformed(evt);
            }
        });

        lblDLNum.setText("Driver License Number");

        txtDLState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDLStateActionPerformed(evt);
            }
        });

        lblDLState.setText("Driver License State");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblSSN.setText("Social Security Number");

        lblWAddressL1.setText("Address Line 1");

        txtWAddressL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWAddressL1ActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        txtWAddressL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWAddressL2ActionPerformed(evt);
            }
        });

        lblWAddressL2.setText("Address Line 2");

        txtWCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWCityActionPerformed(evt);
            }
        });

        lblSex.setText("Sex");

        lblWCity.setText("City");

        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });

        txtWState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWStateActionPerformed(evt);
            }
        });

        lblWState.setText("State");

        txtWZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWZipActionPerformed(evt);
            }
        });

        lblWZip.setText("ZIP");

        txtWPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWPhoneActionPerformed(evt);
            }
        });

        lblWPhone.setText("Work Phone Number");

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        lblFax.setText("FAX Number");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblMStat.setText("Maritial Status");

        lblLang.setText("Language");

        txtLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLangActionPerformed(evt);
            }
        });

        txtMStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMStatActionPerformed(evt);
            }
        });

        lblPWeb.setText("Personal Website");

        txtPWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPWebActionPerformed(evt);
            }
        });

        lblCOri.setText("Country of Origin");

        txtCOri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Person Profile");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblWAddress.setText("Work Address");

        lblLocAddressL1.setText("Address Line 1");

        txtLocAddressL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocAddressL1ActionPerformed(evt);
            }
        });

        txtLocAddressL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocAddressL2ActionPerformed(evt);
            }
        });

        lblLocAddressL2.setText("Address Line 2");

        txtLocCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocCityActionPerformed(evt);
            }
        });

        lblLAddress.setText("Local Address");

        lblLocCity.setText("City");

        txtLocState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocStateActionPerformed(evt);
            }
        });

        lblLocState.setText("State");

        txtLocZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocZipActionPerformed(evt);
            }
        });

        lblLocZip.setText("ZIP");

        txtLocPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocPhoneActionPerformed(evt);
            }
        });

        lblLocPhone.setText("Local Phone Number");

        lblHAddressL2.setText("Address Line 2");

        txtHCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHCityActionPerformed(evt);
            }
        });

        lblHCity.setText("City");

        txtHState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHStateActionPerformed(evt);
            }
        });

        lblHState.setText("State");

        txtHZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHZipActionPerformed(evt);
            }
        });

        lblHZip.setText("ZIP");

        txtHPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPhoneActionPerformed(evt);
            }
        });

        lblHPhone.setText("Home Phone Number");

        lblHAddressL1.setText("Address Line 1");

        txtHAddressL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddressL1ActionPerformed(evt);
            }
        });

        txtHAddressL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddressL2ActionPerformed(evt);
            }
        });

        lblHAddress.setText("Home Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFName)
                                .addGap(18, 18, 18)
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDLState)
                                    .addComponent(lblDLNum)
                                    .addComponent(lblSSN)
                                    .addComponent(lblPhone)
                                    .addComponent(lblWAddress))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDLNum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDLState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWAddressL1)
                                    .addComponent(lblWAddressL2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblWZip)
                                    .addComponent(lblWCity)
                                    .addComponent(lblWState)
                                    .addComponent(lblWPhone))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMStat)
                                    .addComponent(lblLang)
                                    .addComponent(lblPWeb)
                                    .addComponent(lblCOri)
                                    .addComponent(lblAge)
                                    .addComponent(lblSex)
                                    .addComponent(lblFax))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMStat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCOri, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLocAddressL1)
                                            .addComponent(lblLocAddressL2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLocAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLocAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLocZip, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLocCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLocState, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLocPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLocState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLocCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLocZip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLocPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLAddress)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHAddressL1)
                                        .addComponent(lblHAddressL2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHZip, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHState, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblHAddress))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDLNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDLNum))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDLState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDLState))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSex)
                                .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFax)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMStat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPWeb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCOri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCOri))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWAddress)
                    .addComponent(lblLAddress)
                    .addComponent(lblHAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLocAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocAddressL1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLocAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocAddressL2))
                                .addGap(18, 18, 18)
                                .addComponent(txtLocCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLocCity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLocState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocState))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLocZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocZip))
                                .addGap(18, 18, 18)
                                .addComponent(txtLocPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLocPhone, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWAddressL1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWAddressL2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWCity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWState))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWZip))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWPhone)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHAddressL1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHAddressL2))
                                .addGap(18, 18, 18)
                                .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHCity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHState))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHZip))
                                .addGap(18, 18, 18)
                                .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHPhone, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDLNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDLNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDLNumActionPerformed

    private void txtDLStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDLStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDLStateActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtWAddressL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWAddressL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWAddressL1ActionPerformed

    private void txtWAddressL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWAddressL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWAddressL2ActionPerformed

    private void txtWCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWCityActionPerformed

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void txtWStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWStateActionPerformed

    private void txtWZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWZipActionPerformed

    private void txtWPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWPhoneActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLangActionPerformed

    private void txtMStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMStatActionPerformed

    private void txtPWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPWebActionPerformed

    private void txtCOriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOriActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        String email = txtEmail.getText();
        String phone = txtPhone.getText();
        String dLNum = txtDLNum.getText();
        String dLState = txtDLState.getText();
        String socialNum = txtSSN.getText();
        String age = txtAge.getText();
        String sex = txtSex.getText();
        String fax = txtFax.getText();
        String mStat = txtMStat.getText();
        String language = txtLang.getText();
        String perWeb = txtPWeb.getText();
        String conOrigin = txtCOri.getText();
        
        String wAddress1 = txtWAddressL1.getText();
        String wAddress2 = txtWAddressL2.getText();
        String wCity = txtWCity.getText();
        String wState = txtWState.getText();
        String wZip = txtWZip.getText();
        String wPhone = txtWPhone.getText();
        
        String locAddress1 = txtLocAddressL1.getText();
        String locAddress2 = txtLocAddressL2.getText();
        String locCity = txtLocCity.getText();
        String locState = txtLocState.getText();
        String locZip = txtLocZip.getText();
        String locPhone = txtLocPhone.getText();
        
        String hAddress1 = txtHAddressL1.getText();
        String hAddress2 = txtHAddressL2.getText();
        String hCity = txtHCity.getText();
        String hState = txtHState.getText();
        String hZip = txtHZip.getText();
        String hPhone = txtHPhone.getText();
        
        person.setFirstName(fName);
        person.setLastName(lName);
        person.setEmail(email);
        person.setPhone(phone);
        person.setdLicenseNum(dLNum);
        person.setdLicenseState(dLState);
        person.setFaxNum(fax);
        person.setmStat(mStat);
        person.setConOrigin(conOrigin);
        person.setSocialSNum(socialNum);
        person.setSex(sex);
        person.setAge(age);
        person.setPerWeb(perWeb);
        person.setLanguage(language);
        
        person.setwAddress1(wAddress1);
        person.setwAddress2(wAddress2);
        person.setwCity(wCity);
        person.setwPhone(wPhone);
        person.setwState(wState);
        person.setwZip(wZip);
        
        person.setLocAddress1(locAddress1);
        person.setLocAddress2(locAddress2);
        person.setLocCity(locCity);
        person.setLocPhone(locPhone);
        person.setLocState(locState);
        person.setLocZip(locZip);
        
        person.sethAddress1(hAddress1);
        person.sethAddress2(hAddress2);
        person.sethCity(hCity);
        person.sethPhone(hPhone);
        person.sethState(hState);
        person.sethZip(hZip);
        
        JOptionPane.showMessageDialog(this, "Person Saved!", "Success", JOptionPane.PLAIN_MESSAGE);
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtLocAddressL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocAddressL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocAddressL1ActionPerformed

    private void txtLocAddressL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocAddressL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocAddressL2ActionPerformed

    private void txtLocCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocCityActionPerformed

    private void txtLocStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocStateActionPerformed

    private void txtLocZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocZipActionPerformed

    private void txtLocPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocPhoneActionPerformed

    private void txtHCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHCityActionPerformed

    private void txtHStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHStateActionPerformed

    private void txtHZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHZipActionPerformed

    private void txtHPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPhoneActionPerformed

    private void txtHAddressL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddressL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddressL1ActionPerformed

    private void txtHAddressL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddressL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddressL2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCOri;
    private javax.swing.JLabel lblDLNum;
    private javax.swing.JLabel lblDLState;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHAddress;
    private javax.swing.JLabel lblHAddressL1;
    private javax.swing.JLabel lblHAddressL2;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHPhone;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHZip;
    private javax.swing.JLabel lblLAddress;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lblLocAddressL1;
    private javax.swing.JLabel lblLocAddressL2;
    private javax.swing.JLabel lblLocCity;
    private javax.swing.JLabel lblLocPhone;
    private javax.swing.JLabel lblLocState;
    private javax.swing.JLabel lblLocZip;
    private javax.swing.JLabel lblMStat;
    private javax.swing.JLabel lblPWeb;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblWAddress;
    private javax.swing.JLabel lblWAddressL1;
    private javax.swing.JLabel lblWAddressL2;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWPhone;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCOri;
    private javax.swing.JTextField txtDLNum;
    private javax.swing.JTextField txtDLState;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHAddressL1;
    private javax.swing.JTextField txtHAddressL2;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHPhone;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHZip;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtLang;
    private javax.swing.JTextField txtLocAddressL1;
    private javax.swing.JTextField txtLocAddressL2;
    private javax.swing.JTextField txtLocCity;
    private javax.swing.JTextField txtLocPhone;
    private javax.swing.JTextField txtLocState;
    private javax.swing.JTextField txtLocZip;
    private javax.swing.JTextField txtMStat;
    private javax.swing.JTextField txtPWeb;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtWAddressL1;
    private javax.swing.JTextField txtWAddressL2;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWPhone;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWZip;
    // End of variables declaration//GEN-END:variables
}
