/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonManager;

import Model.Person;
import Model.PersonDirectory;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ruirui
 */
public class CreateJPanel extends javax.swing.JPanel {

    Person person;
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    
    /**
     * Creates new form createJPanel
     */
    public CreateJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFName = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblWAddressL1 = new javax.swing.JLabel();
        txtWAddressL1 = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtWAddressL2 = new javax.swing.JTextField();
        lblWAddressL2 = new javax.swing.JLabel();
        txtWCity = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        lblWState = new javax.swing.JLabel();
        txtWZip = new javax.swing.JTextField();
        lblWZip = new javax.swing.JLabel();
        txtWPhone = new javax.swing.JTextField();
        lblWPhone = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblWAddress = new javax.swing.JLabel();
        lblHAddressL2 = new javax.swing.JLabel();
        txtHCity = new javax.swing.JTextField();
        lblHCity = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        txtHZip = new javax.swing.JTextField();
        lblHZip = new javax.swing.JLabel();
        txtHPhone = new javax.swing.JTextField();
        lblHPhone = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblHAddressL1 = new javax.swing.JLabel();
        txtHAddressL1 = new javax.swing.JTextField();
        txtHAddressL2 = new javax.swing.JTextField();
        lblHAddress = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblPersonDetail = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1900, 800));
        setPreferredSize(new java.awt.Dimension(1900, 800));
        setSize(new java.awt.Dimension(1900, 800));

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        lblFName.setText("First Name");

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        lblLName.setText("Last Name");

        lblWAddressL1.setText("Address Line 1");

        txtWAddressL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWAddressL1ActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        txtWAddressL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWAddressL2ActionPerformed(evt);
            }
        });

        lblWAddressL2.setText("Address Line 2");

        txtWCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWCityActionPerformed(evt);
            }
        });

        lblSex.setText("Sex");

        lblWCity.setText("City");

        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });

        txtWState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWStateActionPerformed(evt);
            }
        });

        lblWState.setText("State");

        txtWZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWZipActionPerformed(evt);
            }
        });

        lblWZip.setText("ZIP");

        txtWPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWPhoneActionPerformed(evt);
            }
        });

        lblWPhone.setText("Work Phone Number");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Person Profile");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblWAddress.setText("Work Address");

        lblHAddressL2.setText("Address Line 2");

        txtHCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHCityActionPerformed(evt);
            }
        });

        lblHCity.setText("City");

        txtHState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHStateActionPerformed(evt);
            }
        });

        lblHState.setText("State");

        txtHZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHZipActionPerformed(evt);
            }
        });

        lblHZip.setText("ZIP");

        txtHPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPhoneActionPerformed(evt);
            }
        });

        lblHPhone.setText("Home Phone Number");

        lblHAddressL1.setText("Address Line 1");

        txtHAddressL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddressL1ActionPerformed(evt);
            }
        });

        txtHAddressL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddressL2ActionPerformed(evt);
            }
        });

        lblHAddress.setText("Home Address");

        btnBack.setText("<<Back");

        lblPersonDetail.setText("Personal Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(501, 501, 501)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonDetail)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAge)
                                    .addComponent(lblSex))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblWAddressL1)
                                            .addComponent(lblWAddressL2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblWZip)
                                            .addComponent(lblWCity)
                                            .addComponent(lblWState))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHAddressL1)
                                    .addComponent(lblHAddressL2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHZip)
                                        .addComponent(lblHCity)
                                        .addComponent(lblHState)
                                        .addComponent(lblHPhone))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblHAddress, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWAddress)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWAddressL1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWAddressL2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWState)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPersonDetail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAge)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSex)
                                        .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWZip)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHAddress)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHAddressL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHAddressL1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHAddressL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHAddressL2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHCity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHState))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHZip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHPhone)
                            .addComponent(txtHPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWPhone)
                                .addComponent(btnSave)))))
                .addContainerGap(447, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtWAddressL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWAddressL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWAddressL1ActionPerformed

    private void txtWAddressL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWAddressL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWAddressL2ActionPerformed

    private void txtWCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWCityActionPerformed

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void txtWStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWStateActionPerformed

    private void txtWZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWZipActionPerformed

    private void txtWPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWPhoneActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        String age = txtAge.getText();
        String sex = txtSex.getText();
        
        String wAddress1 = txtWAddressL1.getText();
        String wAddress2 = txtWAddressL2.getText();
        String wCity = txtWCity.getText();
        String wState = txtWState.getText();
        String wZip = txtWZip.getText();
        String wPhone = txtWPhone.getText();
        
        String hAddress1 = txtHAddressL1.getText();
        String hAddress2 = txtHAddressL2.getText();
        String hCity = txtHCity.getText();
        String hState = txtHState.getText();
        String hZip = txtHZip.getText();
        String hPhone = txtHPhone.getText();
        
        if(fName.isBlank() || lName.isBlank() 
            || wAddress1.isBlank() || wAddress2.isBlank()) {
                JOptionPane.showMessageDialog(this,"All Fields Must Been Filled Out!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
        }
        
        Person p = personDirectory.addPerson();
        
        person.setFirstName(fName);
        person.setLastName(lName);
        person.setSex(sex);
        person.setAge(age);

        person.setwAddress1(wAddress1);
        person.setwAddress2(wAddress2);
        person.setwCity(wCity);
        person.setwPhone(wPhone);
        person.setwState(wState);
        person.setwZip(wZip);
        
        person.sethAddress1(hAddress1);
        person.sethAddress2(hAddress2);
        person.sethCity(hCity);
        person.sethPhone(hPhone);
        person.sethState(hState);
        person.sethZip(hZip);
        
        JOptionPane.showMessageDialog(this,"Person Added Successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtHCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHCityActionPerformed

    private void txtHStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHStateActionPerformed

    private void txtHZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHZipActionPerformed

    private void txtHPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPhoneActionPerformed

    private void txtHAddressL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddressL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddressL1ActionPerformed

    private void txtHAddressL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddressL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddressL2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblHAddress;
    private javax.swing.JLabel lblHAddressL1;
    private javax.swing.JLabel lblHAddressL2;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHPhone;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHZip;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPersonDetail;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblWAddress;
    private javax.swing.JLabel lblWAddressL1;
    private javax.swing.JLabel lblWAddressL2;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWPhone;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtHAddressL1;
    private javax.swing.JTextField txtHAddressL2;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHPhone;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHZip;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtWAddressL1;
    private javax.swing.JTextField txtWAddressL2;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWPhone;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWZip;
    // End of variables declaration//GEN-END:variables
}
