/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonManager;

import Model.Person;
import Model.PersonDirectory;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruirui
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    private Person person;
    PersonDirectory personDirectory;
    JPanel userProcessContainer;
    
    /**
     * Creates new form viewJPanle
     */
    public ManagePersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setRequestFocusEnabled(false);
        setSize(new java.awt.Dimension(1200, 800));

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "Sex", "Home Address", "Home Address", "Home City", "Home State", "Home Zip", "Home Phone", "Work Address", "Work Address", "Work City", "Work State", "Work Zip", "Work Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerson);
        if (tblPerson.getColumnModel().getColumnCount() > 0) {
            tblPerson.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblPerson.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblPerson.getColumnModel().getColumn(2).setPreferredWidth(25);
            tblPerson.getColumnModel().getColumn(3).setPreferredWidth(25);
            tblPerson.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblPerson.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblPerson.getColumnModel().getColumn(6).setPreferredWidth(65);
            tblPerson.getColumnModel().getColumn(8).setPreferredWidth(65);
            tblPerson.getColumnModel().getColumn(10).setPreferredWidth(90);
            tblPerson.getColumnModel().getColumn(11).setPreferredWidth(90);
            tblPerson.getColumnModel().getColumn(12).setPreferredWidth(65);
            tblPerson.getColumnModel().getColumn(14).setPreferredWidth(65);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayPerson(){
//        txtFName.setText(person.getFirstName());
//        txtLName.setText(person.getLastName());
//        txtEmail.setText(person.getEmail());
//        txtPhone.setText(person.getPhone());
//        txtDLNum.setText(person.getdLicenseNum());
//        txtDLState.setText(person.getdLicenseState());
//        txtSSN.setText(person.getSocialSNum());
//        txtAge.setText(person.getAge());
//        txtSex.setText(person.getSex());
//        txtFax.setText(person.getFaxNum());
//        txtMStat.setText(person.getmStat());
//        txtLang.setText(person.getLanguage());
//        txtPWeb.setText(person.getPerWeb());
//        txtCOri.setText(person.getConOrigin());
//        
//        txtWAddressL1.setText(person.getwAddress1());
//        txtWAddressL2.setText(person.getwAddress2());
//        txtWCity.setText(person.getwCity());
//        txtWState.setText(person.getwState());
//        txtWZip.setText(person.getwZip());
//        txtWPhone.setText(person.getwPhone());
//        
//        txtHAddressL1.setText(person.gethAddress1());
//        txtHAddressL2.setText(person.gethAddress2());
//        txtHCity.setText(person.gethCity());
//        txtHState.setText(person.gethState());
//        txtHZip.setText(person.gethZip());
//        txtHPhone.setText(person.gethPhone());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerson;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        
        for(Person p : personDirectory.getPerson()) {
            
            Object[] row = new Object[16];
            row[0] = p.getFirstName();
            row[1] = p.getLastName();
            row[2] = p.getAge();
            row[3] = p.getSex();
            
            row[4] = p.gethAddress1();
            row[5] = p.gethAddress2();
            row[6] = p.gethCity();
            row[7] = p.gethState();
            row[8] = p.gethZip();
            row[9] = p.gethPhone();
            
            row[10] = p.getwAddress1();
            row[11] = p.getwAddress2();
            row[12] = p.getwCity();
            row[13] = p.getwState();
            row[14] = p.getwZip();
            row[15] = p.getwPhone();
            
            model.addRow(row);
        }
    }
    
}
