/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonManager;

import Model.Person;
import Model.PersonDirectory;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author ruirui
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    /**
     * Creates new form SearchResJPanel
     */
    public ViewPersonJPanel(JPanel container, PersonDirectory directory, Person person) {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        this.userProcessContainer = container;
        this.personDirectory = directory;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(2300, 900));
        setSize(new java.awt.Dimension(2300, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private void refreshTextFields() {
//        txtRouteNum.setText(account.getRouteNum());
//        txtAccNum.setText(account.getAccNum());
//        txtBankName.setText(account.getBankName());
    }

    private void setViewMode() {
//        txtRouteNum.setEnabled(false);
//        txtAccNum.setEnabled(false);
//        txtBankName.setEnabled(false);
//        
//        btnSave.setEnabled(false);
//        btnUpdate.setEnabled(true);
    }
    
    private void setEditMode() {
//        txtRouteNum.setEnabled(true);
//        txtAccNum.setEnabled(true);
//        txtBankName.setEnabled(true);
//        
//        btnSave.setEnabled(true);
//        btnUpdate.setEnabled(false);
    }
}
