/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Main;

import Model.Person;
import Model.PersonDirectory;
import UI.PersonManager.PersonMngWorkArea;
import java.awt.CardLayout;

/**
 *
 * @author ruirui
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private PersonDirectory personDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnPersonMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1900, 1000));
        setSize(new java.awt.Dimension(1900, 1000));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setPreferredSize(new java.awt.Dimension(1900, 1000));
        topJPanel.setSize(new java.awt.Dimension(1900, 1000));

        lblWelcome.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome to the Person Viewer Application!");

        btnPersonMng.setFont(new java.awt.Font("Apple LiGothic", 1, 15)); // NOI18N
        btnPersonMng.setText("Open Person Viewer Work Area");
        btnPersonMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome)
                    .addComponent(btnPersonMng))
                .addContainerGap(1526, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonMng)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        userProcessContainer.setMinimumSize(new java.awt.Dimension(1200, 800));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(1200, 800));
        userProcessContainer.setSize(new java.awt.Dimension(1200, 800));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonMngActionPerformed
        // TODO add your handling code here:
        PersonMngWorkArea panel = new PersonMngWorkArea(userProcessContainer, personDirectory);
        userProcessContainer.add("AccMngWorkAreaJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonMng;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        Person newPerson1 = personDirectory.addPerson();
        newPerson1.setFirstName("John");
        newPerson1.setLastName("Doe");
        newPerson1.setAge("18");
        newPerson1.setSex("M");

        newPerson1.setwAddress1("Boston Ave");
        newPerson1.setwAddress2("Room.101");
        newPerson1.setwCity("Boston");
        newPerson1.setwState("MA");
        newPerson1.setwZip("02120");
        newPerson1.setwPhone("3210009");
        
        newPerson1.sethAddress1("Main St");
        newPerson1.sethAddress2("Apt.202");
        newPerson1.sethCity("Miami");
        newPerson1.sethState("FL");
        newPerson1.sethZip("31000");
        newPerson1.sethPhone("1170088");
        
        Person newPerson2 = personDirectory.addPerson();
        newPerson2.setFirstName("Mary");
        newPerson2.setLastName("Jane");
        newPerson2.setAge("26");
        newPerson2.setSex("F");

        newPerson2.setwAddress1("French Ave");
        newPerson2.setwAddress2("No.2002");
        newPerson2.setwCity("Chelsea");
        newPerson2.setwState("MA");
        newPerson2.setwZip("02150");
        newPerson2.setwPhone("908880");
        
        newPerson2.sethAddress1("Geneva St");
        newPerson2.sethAddress2("Room.230");
        newPerson2.sethCity("Malden");
        newPerson2.sethState("MA");
        newPerson2.sethZip("02230");
        newPerson2.sethPhone("807008");
        
        Person newPerson3 = personDirectory.addPerson();
        newPerson3.setFirstName("Will");
        newPerson3.setLastName("Brown");
        newPerson3.setAge("32");
        newPerson3.setSex("M");

        newPerson3.setwAddress1("Forest Ave");
        newPerson3.setwAddress2("1755");
        newPerson3.setwCity("Boston");
        newPerson3.setwState("MA");
        newPerson3.setwZip("02140");
        newPerson3.setwPhone("617893");
        
        newPerson3.sethAddress1("Clay St");
        newPerson3.sethAddress2("No.432");
        newPerson3.sethCity("Concord");
        newPerson3.sethState("NH");
        newPerson3.sethZip("03103");
        newPerson3.sethPhone("8490023");
    }
    
}
